version: "2"
services:
  redis:
    image: redis:3
    container_name: perfload.redis
    ports:
      - 6379:6379
    logging:
      driver: none
  redis-commander:
    image: tenstartups/redis-commander
    container_name: perfload.redis-commander
    command: --redis-host redis
    ports:
      - 6380:8081
    links:
      - redis
    logging:
      driver: none
  mongo:
    image: mongo
    container_name: perfload.mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: perf-data
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root